version: 0.2

env:
  variables:
    APP: resources-api
    ECR_URL: 871541556194.dkr.ecr.us-east-2.amazonaws.com/bookstore.resources-api
    ECR_REPO_NAME: bookstore.resources-api

phases:
  pre_build:
    commands:
      - echo "Checking for version file..."
      - if [ -f `pwd`/version ]; then source `pwd`/version; else echo "version file not found, using default version"; MAJOR=0; MINOR=1; fi
      - COMMIT_ID_SHORT=`echo "${CODEBUILD_RESOLVED_SOURCE_VERSION}" | cut -c1-8`
      - TAG=`echo "${MAJOR}.${MINOR}.${COMMIT_ID_SHORT}"`
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${ECR_URL}
  build:  
    commands:
      - docker build -t ${APP}:${TAG} -f resources-api/src/Dockerfile resources-api/src
      - docker tag ${APP}:${TAG} ${ECR_URL}/${ECR_REPO_NAME}:${TAG}
  post_build:
    commands:
      - docker push ${ECR_URL}/${ECR_REPO_NAME}:${TAG}
